[package]
name = "contracts"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = "2.0.0"
starknet = "2.11.4"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.46.0" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "c804e98" }
openzeppelin_token = "2.0.0"
vesu = { git = "https://github.com/vesuxyz/vesu-v2.git" }

[dev-dependencies]
assert_macros = "2.11.4"

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[[target.starknet-contract]]
sierra = true
casm = true
