[package]
name = "vault-watcher"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.15.7"
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
